/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as UrgencesRouteImport } from './routes/urgences'
import { Route as SmsRouteImport } from './routes/sms'
import { Route as SecuriteRouteImport } from './routes/securite'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FamilleRouteImport } from './routes/famille'
import { Route as AlertesRouteImport } from './routes/alertes'
import { Route as IndexRouteImport } from './routes/index'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const UrgencesRoute = UrgencesRouteImport.update({
  id: '/urgences',
  path: '/urgences',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsRoute = SmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const SecuriteRoute = SecuriteRouteImport.update({
  id: '/securite',
  path: '/securite',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilleRoute = FamilleRouteImport.update({
  id: '/famille',
  path: '/famille',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertesRoute = AlertesRouteImport.update({
  id: '/alertes',
  path: '/alertes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertes': typeof AlertesRoute
  '/famille': typeof FamilleRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/reset-password': typeof ResetPasswordRoute
  '/securite': typeof SecuriteRoute
  '/sms': typeof SmsRoute
  '/urgences': typeof UrgencesRoute
  '/verify-email': typeof VerifyEmailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertes': typeof AlertesRoute
  '/famille': typeof FamilleRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/reset-password': typeof ResetPasswordRoute
  '/securite': typeof SecuriteRoute
  '/sms': typeof SmsRoute
  '/urgences': typeof UrgencesRoute
  '/verify-email': typeof VerifyEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertes': typeof AlertesRoute
  '/famille': typeof FamilleRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/reset-password': typeof ResetPasswordRoute
  '/securite': typeof SecuriteRoute
  '/sms': typeof SmsRoute
  '/urgences': typeof UrgencesRoute
  '/verify-email': typeof VerifyEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertes'
    | '/famille'
    | '/login'
    | '/parametres'
    | '/reset-password'
    | '/securite'
    | '/sms'
    | '/urgences'
    | '/verify-email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertes'
    | '/famille'
    | '/login'
    | '/parametres'
    | '/reset-password'
    | '/securite'
    | '/sms'
    | '/urgences'
    | '/verify-email'
  id:
    | '__root__'
    | '/'
    | '/alertes'
    | '/famille'
    | '/login'
    | '/parametres'
    | '/reset-password'
    | '/securite'
    | '/sms'
    | '/urgences'
    | '/verify-email'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertesRoute: typeof AlertesRoute
  FamilleRoute: typeof FamilleRoute
  LoginRoute: typeof LoginRoute
  ParametresRoute: typeof ParametresRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecuriteRoute: typeof SecuriteRoute
  SmsRoute: typeof SmsRoute
  UrgencesRoute: typeof UrgencesRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urgences': {
      id: '/urgences'
      path: '/urgences'
      fullPath: '/urgences'
      preLoaderRoute: typeof UrgencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms': {
      id: '/sms'
      path: '/sms'
      fullPath: '/sms'
      preLoaderRoute: typeof SmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/securite': {
      id: '/securite'
      path: '/securite'
      fullPath: '/securite'
      preLoaderRoute: typeof SecuriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/famille': {
      id: '/famille'
      path: '/famille'
      fullPath: '/famille'
      preLoaderRoute: typeof FamilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertes': {
      id: '/alertes'
      path: '/alertes'
      fullPath: '/alertes'
      preLoaderRoute: typeof AlertesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertesRoute: AlertesRoute,
  FamilleRoute: FamilleRoute,
  LoginRoute: LoginRoute,
  ParametresRoute: ParametresRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecuriteRoute: SecuriteRoute,
  SmsRoute: SmsRoute,
  UrgencesRoute: UrgencesRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
