# Generated by Django 6.0.5 on 2026-06-04 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('alerte_gaz', 'Alerte gaz'), ('systeme_inactif', 'Système inactif'), ('demande_approbation', "Demande d'approbation")], default='alerte_gaz', max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='alerte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.alerte'),
        ),
    ]
