# Generated by Django 6.0.5 on 2026-06-05 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification_message_notification_type_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationFoyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('est_consomme', models.BooleanField(default=False)),
                ('foyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.foyer')),
            ],
            options={
                'verbose_name': 'Invitation Foyer',
                'db_table': 'invitation_foyer',
            },
        ),
    ]
