# Generated by Django 6.0.5 on 2026-06-08 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invitationfoyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TokenEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('type_token', models.CharField(choices=[('verification', 'Vérification'), ('reinitialisation', 'Réinitialisation')], max_length=20)),
                ('date_expiration', models.DateTimeField()),
                ('est_utilise', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_email', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'token_email',
            },
        ),
    ]
