# Generated by Django 6.0.5 on 2026-06-10 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_foyer_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foyer',
            name='token',
        ),
    ]
