# Generated by Django 6.0.5 on 2026-06-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_foyer_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='foyer',
            name='adresse_repere',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
